# Generated by Django 5.1.7 on 2025-05-25 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("fullName", models.CharField(blank=True, max_length=120, null=True)),
                ("email", models.EmailField(blank=True, max_length=120, null=True)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "deliveryType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORDINARY", "ordinary"),
                            ("EXPRESS", "express"),
                            ("COURIER_DELIVERY", "courier_delivery"),
                            ("PICKUP", "pickup"),
                            ("PICKUP_POINT", "pickup_point"),
                            ("PARCEL_LOCKER", "parcel_locker"),
                            ("POSTAL_DELIVERY", "postal_delivery"),
                            ("FREIGHT_DELIVERY", "freight_delivery"),
                        ],
                        default="ORDINARY",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONLINE", "online"),
                            ("SOMEONE", "someone"),
                            ("SBP", "через систему быстрых платежей"),
                            ("CRYPTO", "криптовалюта"),
                            ("E_WALLET", "электронный кошелек"),
                            ("CASH", "оплата наличными при получении"),
                            ("NON_CASH_PAYMENT", "безналичный расчет"),
                            ("INSTALLMENT_PURCHASE", "покупка в рассрочку"),
                            ("MOBILE_PAYMENTS", "мобильные платежи"),
                        ],
                        default="ONLINE",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "new"),
                            ("ACCEPTED", "accepted"),
                            ("AWAITING_PAYMENT", "awaiting_payment"),
                            ("PAIDED", "paided"),
                            ("PROCESSING", "processing"),
                            ("READY_TO_SHIP", "ready_to_ship"),
                            ("SHIPPED", "shipped"),
                            ("DELIVERED", "delivered"),
                            ("CANCELLED", "cancelled"),
                            ("RETURNED", "returned"),
                        ],
                        default="NEW",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("address", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["createdAt"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=16, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("month", models.CharField(blank=True, max_length=2, null=True)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                ("code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders_app.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders_app.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderProduct",
                        to="products_app.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказах",
                "unique_together": {("order", "product")},
            },
        ),
    ]
