# Generated by Django 5.1.7 on 2025-06-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordinary_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=200,
                        max_digits=10,
                        verbose_name="Стоимость обычной доставки",
                    ),
                ),
                (
                    "express_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=10,
                        verbose_name="Стоимость экспресс доставки",
                    ),
                ),
                (
                    "free_delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        max_digits=10,
                        verbose_name="Стоимость заказа для бесплатной доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ доставки",
                "verbose_name_plural": "Способ доставки",
            },
        ),
    ]
