# Generated by Django 5.1.7 on 2025-06-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0002_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                blank=True,
                choices=[("ORDINARY", "ordinary"), ("EXPRESS", "express")],
                default="ORDINARY",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                blank=True,
                choices=[("ONLINE", "online"), ("SOMEONE", "someone")],
                default="ONLINE",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "new"),
                    ("ACCEPTED", "accepted"),
                    ("AWAITING_PAYMENT", "awaiting_payment"),
                    ("PAIDED", "paided"),
                ],
                default="NEW",
                max_length=100,
                null=True,
            ),
        ),
    ]
