# Generated by Django 5.1.7 on 2025-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_app",
            "0003_alter_order_deliverytype_alter_order_paymenttype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "new"),
                    ("ACCEPTED", "accepted"),
                    ("AWAITING_PAYMENT", "awaiting_payment"),
                    ("PAYMENT_ERROR", "payment_error"),
                    ("PAIDED", "paided"),
                ],
                default="NEW",
                max_length=100,
                null=True,
            ),
        ),
    ]
