# Generated by Django 5.1.7 on 2025-06-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-createdAt"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
