# Generated by Django 5.1.7 on 2025-07-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0005_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name": "Доставка", "verbose_name_plural": "Доставка"},
        ),
    ]
