# Generated by Django 5.1.7 on 2025-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0006_alter_delivery_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
