# Generated by Django 5.1.11 on 2025-08-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0007_alter_payment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "new"),
                    ("CONFIRMED", "confirmed"),
                    ("AWAITING_PAYMENT", "awaiting_payment"),
                    ("PAYMENT_ERROR", "payment_error"),
                    ("PAIDED", "paided"),
                ],
                default="NEW",
                max_length=100,
                null=True,
            ),
        ),
    ]
