# Generated by Django 5.1.11 on 2025-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
