# Generated by Django 5.1.11 on 2025-08-17 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0009_order_available"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                max_length=120, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                max_length=120, null=True, verbose_name="Город доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[("ORDINARY", "ordinary"), ("EXPRESS", "express")],
                default="ORDINARY",
                max_length=100,
                null=True,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                max_length=120, null=True, verbose_name="Email получателя"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fullName",
            field=models.CharField(
                max_length=120, null=True, verbose_name="Полное имя получателя"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                choices=[("ONLINE", "online"), ("SOMEONE", "someone")],
                default="ONLINE",
                max_length=100,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=11, null=True, verbose_name="Телефон получателя"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "new"),
                    ("CONFIRMED", "confirmed"),
                    ("AWAITING_PAYMENT", "awaiting_payment"),
                    ("PAYMENT_ERROR", "payment_error"),
                    ("PAIDED", "paided"),
                ],
                default="NEW",
                max_length=100,
                null=True,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Итоговая стоимость заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
