# Generated by Django 5.1.11 on 2025-08-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0010_alter_order_address_alter_order_available_and_more"),
        ("products_app", "0003_productreview_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="count",
            field=models.PositiveIntegerField(
                default=1, null=True, verbose_name="Количество товара в заказе"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="orders_app.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая цена на момент покупки",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderProduct",
                to="products_app.product",
                verbose_name="Товар в заказе",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="code",
            field=models.CharField(max_length=3, null=True, verbose_name="Код карты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.CharField(
                max_length=2, null=True, verbose_name="Месяц выпуска карты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Имя владельца карты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(max_length=8, null=True, verbose_name="Номер карты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="orders_app.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.CharField(
                max_length=4, null=True, verbose_name="Год выпуска карты"
            ),
        ),
    ]
