# Generated by Django 5.1.11 on 2025-08-17 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_app",
            "0011_alter_orderproduct_added_at_alter_orderproduct_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата оплаты",
            ),
            preserve_default=False,
        ),
    ]
