# Generated by Django 5.1.11 on 2025-08-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0012_payment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]
