"""
Django settings for mainsite project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from os import getenv, environ
from typing import Iterable, Never

from decouple import config, Config, Csv, AutoConfig, RepositoryEnv

from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).parent.parent.resolve().absolute()

# Setup environment mode:
ENV_MODE = config("ENV_MODE", default="development")
if ENV_MODE == "development":
    env_file_path = BASE_DIR.parent / ".env.dev"
    config = Config(RepositoryEnv(env_file_path))
    print("ENV_MODE:", ENV_MODE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-ra_fw(tbekj(s_au*8rjphwjm9f=(r6-_1$6tt8fl7c-ohpx#q",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=0, cast=int) == 1
if DEBUG:
    print(f"DEBUG_MODE: {DEBUG}")


# Setup ALLOWED_HOSTS
ALLOWED_HOSTS: str | Iterable[Never] = config(
    "DJANGO_ALLOWED_HOSTS", default="127.0.0.1, localhost", cast=Csv()
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "rest_framework",
    "django_filters",
    "frontend",
    "auth_app",
    "catalog_app",
    "products_app",
    "tags_app",
    "basket_app",
    "profile_app",
    "orders_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mainsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mainsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_ENGINE = config("DB_ENGINE", default="sqlite")

if DB_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT", cast=int),
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "database" / "db.sqlite3",
        },
    }

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Login settings
LOGIN_URL = reverse_lazy("auth_app:sign_in")
LOGOUT_URL = reverse_lazy("auth_app:sign_out")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / "static"  # Путь к папке в файловой системе
STATIC_ROOT.mkdir(exist_ok=True)  # Создаем папку, если ее нет
STATIC_URL = "static/"  # Путь, который указывается в адресной строке

MEDIA_URL = "media/"  # Путь, который указывается в адресной строке
MEDIA_ROOT = BASE_DIR / "uploads"  # Путь к папке в файловой системе
MEDIA_ROOT.mkdir(exist_ok=True)  # Создаем папку, если ее нет


# Fixtures settings
FIXTURE_DIRS = [BASE_DIR / "fixtures"]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django rest framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    # "DEFAULT_PAGINATION_CLASS": "catalog_app.pagination.CustomPagination",
    # "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    # "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_SCHEMA_CLASS": "mainsite.open_api_utils.AutoSchemaWithDeleteMethod",
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Marketplace API",
    "DESCRIPTION": "Marketplace",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {"name": "auth"},
        {"name": "catalog"},
        {"name": "basket"},
        {"name": "order"},
        {"name": "payment"},
        {"name": "profile"},
        {"name": "tags"},
        {"name": "product"},
    ],
}

# Extra options
APPEND_SLASH = True

# Secure settings
## Количество секунд блокировки незащищенного HTTP подключения:
SECURE_HSTS_SECONDS = 0
## При обращении с HTTP делает редирект на HTTPS:
SECURE_SSL_REDIRECT = False
## Отправка файла cookie сессии только по HTTPS-соединению:
SESSION_COOKIE_SECURE = False
## Отправка файла cookie для CSRF-cookie только по HTTPS-соединению:
CSRF_COOKIE_SECURE = False


# Настройка DEBUG режима
if DEBUG:
    # Добавляем в INSTALLED_APPS 'debug-toolbar'
    INSTALLED_APPS += ["debug_toolbar"]

    # Добавляем в MIDDLEWARES:
    # - XForwardedForMiddleware, который определяет реальный
    #   адреса клиента, проброшенный сервером Nginx в приложение;
    # - DebugToolbarMiddleware, обрабатывающий запросы к 'debug-toolbar'
    MIDDLEWARE = [
        "mainsite.middleware.XForwardedForMiddleware",
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ] + MIDDLEWARE[:]

    # Настройка 'debug-toolbar'
    DEBUG_TOOLBAR_CONFIG = {"IS_RUNNING_TESTS": False}

    # Настройка INTERNAL_IPS для работы 'debug-toolbar'
    import socket

    INTERNAL_IPS = ["127.0.0.1"]
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS.extend([ip[: ip.rfind(".")] + ".1" for ip in ips])
