# Generated by Django 5.1.7 on 2025-08-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basketitem",
            options={
                "verbose_name": "Товары в корзине",
                "verbose_name_plural": "Товары в корзинах",
            },
        ),
    ]
