# Generated by Django 5.1.11 on 2025-08-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket_app", "0002_alter_basketitem_options"),
        ("products_app", "0003_productreview_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="basket_app.basket",
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basket_item",
                to="products_app.product",
                verbose_name="Товар в корзине",
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество товара в корзине"
            ),
        ),
    ]
