# Generated by Django 5.1.11 on 2025-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products_app",
            "0004_alter_product_available_alter_product_category_and_more",
        ),
        ("tags_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название метки"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="products",
            field=models.ManyToManyField(
                related_name="tags", to="products_app.product", verbose_name="Товар"
            ),
        ),
    ]
