# Generated by Django 5.1.11 on 2025-08-17 12:36

import django.db.models.deletion
import profile_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0003_profile_available_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="alt",
            field=models.CharField(max_length=50, null=True, verbose_name="Имя файла"),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="profile_app.profile",
                verbose_name="Профиль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                null=True,
                upload_to=profile_app.models.upload_avatar,
                verbose_name="Источник изображения",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="Email пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullName",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Полное имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="Телефон пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
