# Generated by Django 5.1.11 on 2025-08-17 12:24

import django.core.validators
import django.db.models.deletion
import products_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_app", "0003_category_available_alter_category_favorite_and_more"),
        ("products_app", "0003_productreview_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog_app.category",
                verbose_name="Категория товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Доступное количество товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткое описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(
                default=False, verbose_name="Наличие бесплатной доставки"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(
                blank=True, null=True, verbose_name="Полное описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False, verbose_name="Ограниченный товар"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название товара"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя файла"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products_app.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(
                upload_to=products_app.models.upload_product_image_to,
                verbose_name="Источник изображения",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Имя автора отзыва"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата публикации отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email автора отзыва"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products_app.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Rate must be between 1 and 5"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="Rate must be between 1 and 5"
                    ),
                ],
                verbose_name="Оценка товара",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Имя свойства"
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="products_app.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Значение свойства"
            ),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="dateFrom",
            field=models.DateField(verbose_name="Дата начала распродажи"),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="dateTo",
            field=models.DateField(verbose_name="Дата окончания распродажи"),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="discount",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Значение скидки",
            ),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_items",
                to="products_app.product",
                verbose_name="Товар на распродаже",
            ),
        ),
        migrations.AlterField(
            model_name="saleitems",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products_app.sales",
                verbose_name="Распродажа",
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание распродажи"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название распродажи"),
        ),
    ]
