# Generated by Django 5.1.11 on 2025-08-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products_app",
            "0004_alter_product_available_alter_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products_app.product",
                verbose_name="Товар",
            ),
        ),
    ]
