# Generated by Django 5.1.7 on 2025-05-25 16:12

import catalog_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=catalog_app.models.category_image_path,
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Изображение категории",
                "verbose_name_plural": "Изображения категорий",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="catalog_app.category",
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="catalog_app.categoryimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товаров",
                "verbose_name_plural": "Категории товаров",
                "ordering": ["title"],
            },
        ),
    ]
