# Generated by Django 5.1.7 on 2025-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
