# Generated by Django 5.1.11 on 2025-08-17 08:36

import catalog_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_app", "0002_category_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступна"),
        ),
        migrations.AlterField(
            model_name="category",
            name="favorite",
            field=models.BooleanField(default=False, verbose_name="В избранных"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="catalog_app.categoryimage",
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="catalog_app.category",
                verbose_name="Общая категория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="alt",
            field=models.CharField(max_length=50, null=True, verbose_name="Имя файла"),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="src",
            field=models.ImageField(
                null=True,
                upload_to=catalog_app.models.category_image_path,
                verbose_name="Источник изображения",
            ),
        ),
    ]
